[package]
name = "cryptopals_lib"
version = "0.1.0"
authors = ["Lauri Halla-aho <lhalla@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
base64 = "0.11"